//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Name.
        /// </summary>
        public static string AnimalName {
            get {
                return ResourceManager.GetString("AnimalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Name.
        /// </summary>
        public static string AnimalTypeName {
            get {
                return ResourceManager.GetString("AnimalTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Address.
        /// </summary>
        public static string ArbAddress {
            get {
                return ResourceManager.GetString("ArbAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure ?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breeds.
        /// </summary>
        public static string Breed {
            get {
                return ResourceManager.GetString("Breed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breed Name.
        /// </summary>
        public static string BreedName {
            get {
                return ResourceManager.GetString("BreedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The animal cannot be deleted because it is associated with a physical examination.
        /// </summary>
        public static string CantDeleteAnimal {
            get {
                return ResourceManager.GetString("CantDeleteAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The animal type cannot be deleted because it is associated with a animal.
        /// </summary>
        public static string CantDeleteAnimalType {
            get {
                return ResourceManager.GetString("CantDeleteAnimalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The breed cannot be deleted because it is associated with a Animal.
        /// </summary>
        public static string CantDeleteBreed {
            get {
                return ResourceManager.GetString("CantDeleteBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city cannot be deleted because it is associated with owner information.
        /// </summary>
        public static string CantDeleteCity {
            get {
                return ResourceManager.GetString("CantDeleteCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coat colour cannot be deleted because it is associated with a animal.
        /// </summary>
        public static string CantDeleteCoatColour {
            get {
                return ResourceManager.GetString("CantDeleteCoatColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country cannot be deleted because it is associated with a city.
        /// </summary>
        public static string CantDeleteCountry {
            get {
                return ResourceManager.GetString("CantDeleteCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location of microchip cannot be deleted because it is associated with a animal.
        /// </summary>
        public static string CantDeleteLocationOfMicrochip {
            get {
                return ResourceManager.GetString("CantDeleteLocationOfMicrochip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner cannot be deleted because it is associated with a animal.
        /// </summary>
        public static string CantDeleteOwner {
            get {
                return ResourceManager.GetString("CantDeleteOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Name.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Close .
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coat Colour.
        /// </summary>
        public static string CoatColour {
            get {
                return ResourceManager.GetString("CoatColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coat Colour .
        /// </summary>
        public static string CoatColourName {
            get {
                return ResourceManager.GetString("CoatColourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Info.
        /// </summary>
        public static string CompanyInfo {
            get {
                return ResourceManager.GetString("CompanyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company data and files are being created, 
        ///The installation process may take 1 to 2 minutes, please do not close the screen.
        /// </summary>
        public static string CreateCompanyData {
            get {
                return ResourceManager.GetString("CreateCompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng.
        /// </summary>
        public static string CurLang {
            get {
                return ResourceManager.GetString("CurLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Microchipping.
        /// </summary>
        public static string DateOfMicrochipping {
            get {
                return ResourceManager.GetString("DateOfMicrochipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string Definitions {
            get {
                return ResourceManager.GetString("Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Delete .
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Species.
        /// </summary>
        public static string DeleteAnimalType {
            get {
                return ResourceManager.GetString("DeleteAnimalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Breed.
        /// </summary>
        public static string DeleteBreed {
            get {
                return ResourceManager.GetString("DeleteBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete City.
        /// </summary>
        public static string DeleteCity {
            get {
                return ResourceManager.GetString("DeleteCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Coat Colour.
        /// </summary>
        public static string DeleteCoatColour {
            get {
                return ResourceManager.GetString("DeleteCoatColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Country.
        /// </summary>
        public static string DeleteCountry {
            get {
                return ResourceManager.GetString("DeleteCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Description Of Animal.
        /// </summary>
        public static string DeleteDescriptionOfAnimal {
            get {
                return ResourceManager.GetString("DeleteDescriptionOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Details Of Ownership.
        /// </summary>
        public static string DeleteDetailsOfOwnership {
            get {
                return ResourceManager.GetString("DeleteDetailsOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Location Of Microchip.
        /// </summary>
        public static string DeleteLocationOfMicrochip {
            get {
                return ResourceManager.GetString("DeleteLocationOfMicrochip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Of Ownership.
        /// </summary>
        public static string DetailsOfOwnership {
            get {
                return ResourceManager.GetString("DetailsOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Of Animal.
        /// </summary>
        public static string DiscriptionOfAnimal {
            get {
                return ResourceManager.GetString("DiscriptionOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string EmptyTable {
            get {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Address.
        /// </summary>
        public static string EngAddress {
            get {
                return ResourceManager.GetString("EngAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string InfoEmpty {
            get {
                return ResourceManager.GetString("InfoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        public static string InfoFiltered {
            get {
                return ResourceManager.GetString("InfoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Date Time.
        /// </summary>
        public static string InsDateTime {
            get {
                return ResourceManager.GetString("InsDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert User Name.
        /// </summary>
        public static string InsUserName {
            get {
                return ResourceManager.GetString("InsUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string LengthMenu {
            get {
                return ResourceManager.GetString("LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is being verified.
        /// </summary>
        public static string LoadingMsg {
            get {
                return ResourceManager.GetString("LoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingRecords {
            get {
                return ResourceManager.GetString("LoadingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Of Microchip.
        /// </summary>
        public static string LocationOfMicrochip {
            get {
                return ResourceManager.GetString("LocationOfMicrochip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Of Microchip.
        /// </summary>
        public static string LocationOfMicrochipName {
            get {
                return ResourceManager.GetString("LocationOfMicrochipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Path.
        /// </summary>
        public static string LogoPath {
            get {
                return ResourceManager.GetString("LogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Setup.
        /// </summary>
        public static string MainSetup {
            get {
                return ResourceManager.GetString("MainSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microchip Number.
        /// </summary>
        public static string MicrochipNumber {
            get {
                return ResourceManager.GetString("MicrochipNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Examination.
        /// </summary>
        public static string PhysicalExamination {
            get {
                return ResourceManager.GetString("PhysicalExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Create Your Company Profile First.
        /// </summary>
        public static string PleaseCreateYourCompanyProfileFisrt {
            get {
                return ResourceManager.GetString("PleaseCreateYourCompanyProfileFisrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all  Required fields.
        /// </summary>
        public static string PleasefillalRequiredfields {
            get {
                return ResourceManager.GetString("PleasefillalRequiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Print Excel .
        /// </summary>
        public static string PrintExcel {
            get {
                return ResourceManager.GetString("PrintExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save .
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Species.
        /// </summary>
        public static string SaveAnimalType {
            get {
                return ResourceManager.GetString("SaveAnimalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Breeds.
        /// </summary>
        public static string SaveBreed {
            get {
                return ResourceManager.GetString("SaveBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Cities.
        /// </summary>
        public static string SaveCity {
            get {
                return ResourceManager.GetString("SaveCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Coat Colours.
        /// </summary>
        public static string SaveCoatColour {
            get {
                return ResourceManager.GetString("SaveCoatColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Countries.
        /// </summary>
        public static string SaveCountry {
            get {
                return ResourceManager.GetString("SaveCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Description Of Animal.
        /// </summary>
        public static string SaveDescriptionOfAnimal {
            get {
                return ResourceManager.GetString("SaveDescriptionOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Details Of Ownership.
        /// </summary>
        public static string SaveDetailsOfOwnership {
            get {
                return ResourceManager.GetString("SaveDetailsOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Location Of Microchips.
        /// </summary>
        public static string SaveLocationOfMicrochip {
            get {
                return ResourceManager.GetString("SaveLocationOfMicrochip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Search .
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For The Animal.
        /// </summary>
        public static string SearchAnimals {
            get {
                return ResourceManager.GetString("SearchAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For The Owner.
        /// </summary>
        public static string SearchOwners {
            get {
                return ResourceManager.GetString("SearchOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string Serial {
            get {
                return ResourceManager.GetString("Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        public static string SomthingWentWrong {
            get {
                return ResourceManager.GetString("SomthingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate to sort column ascending :.
        /// </summary>
        public static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate to sort column descending :.
        /// </summary>
        public static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeleFax.
        /// </summary>
        public static string TeleFax {
            get {
                return ResourceManager.GetString("TeleFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Update .
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update  Species.
        /// </summary>
        public static string UpdateAnimalType {
            get {
                return ResourceManager.GetString("UpdateAnimalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Breed.
        /// </summary>
        public static string UpdateBreed {
            get {
                return ResourceManager.GetString("UpdateBreed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update City.
        /// </summary>
        public static string UpdateCity {
            get {
                return ResourceManager.GetString("UpdateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Coat Colour.
        /// </summary>
        public static string UpdateCoatColour {
            get {
                return ResourceManager.GetString("UpdateCoatColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Country.
        /// </summary>
        public static string UpdateCountry {
            get {
                return ResourceManager.GetString("UpdateCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Description Of Animal.
        /// </summary>
        public static string UpdateDescriptionOfAnimal {
            get {
                return ResourceManager.GetString("UpdateDescriptionOfAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Details Of Ownership.
        /// </summary>
        public static string UpdateDetailsOfOwnership {
            get {
                return ResourceManager.GetString("UpdateDetailsOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Location Of Microchip.
        /// </summary>
        public static string UpdateLocationOfMicrochip {
            get {
                return ResourceManager.GetString("UpdateLocationOfMicrochip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updting.
        /// </summary>
        public static string Updting {
            get {
                return ResourceManager.GetString("Updting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your company data in this screen  before you start using the system.
        /// </summary>
        public static string WelcomeCoInfo {
            get {
                return ResourceManager.GetString("WelcomeCoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To CatnipSoft .
        /// </summary>
        public static string WelcomeToCatnipSoft {
            get {
                return ResourceManager.GetString("WelcomeToCatnipSoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Is Being Created.
        /// </summary>
        public static string YourAccountIsBeingCreated {
            get {
                return ResourceManager.GetString("YourAccountIsBeingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company has been established successfully.
        /// </summary>
        public static string YourCompanyEstablished {
            get {
                return ResourceManager.GetString("YourCompanyEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has Been Successfully Sent.
        /// </summary>
        public static string YourrequesthasBeenSuccessfullySent {
            get {
                return ResourceManager.GetString("YourrequesthasBeenSuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string ZeroRecords {
            get {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
