// <auto-generated />
namespace PetsWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class skjdhakjdhjkahsdyh555sd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(skjdhakjdhjkahsdyh555sd));
        
        string IMigrationMetadata.Id
        {
            get { return "202003121209347_skjdhakjdhjkahsdyh555sd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
