// <auto-generated />
namespace PetsWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mohammedawad120220201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mohammedawad120220201));
        
        string IMigrationMetadata.Id
        {
            get { return "202002122113224_mohammedawad120220201"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
