// <auto-generated />
namespace PetsWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MohammedAwad100320202 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MohammedAwad100320202));
        
        string IMigrationMetadata.Id
        {
            get { return "202003112039137_MohammedAwad100320202"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
