// <auto-generated />
namespace PetsWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class skjdhakjdhjkahsdyh555sddf1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(skjdhakjdhjkahsdyh555sddf1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003121251030_skjdhakjdhjkahsdyh555sddf1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
